name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Run npm ci 
      run: npm ci
    - name: Run npm format
      run: npm run format
    - name: Run npm lint
      run: npm run lint
    - name: Run npm test
      run: npm run test