name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
    - name: Install dependencies
      run: npm ci
    - name: Format typescript
      run: npm run format
    - name: Lint typescript
      run: npm run lint-ts
    # - name: Lint commits
    #   run: npm run lint-commit
    - name: Build gyp
      run: npm run build-gyp
    - name: Build typescript
      run: npm run build-ts
    - name: Set up WireGuard
      uses: egor-tensin/setup-wireguard@v1
      with:
        endpoint: '${{ secrets.ENDPOINT }}'
        endpoint_public_key: '${{ secrets.ENDPOINT_PUBLIC }}'
        ips: '${{ secrets.IPS }}'
        allowed_ips: '${{ secrets.ALLOWED_IPS }}'
        private_key: '${{ secrets.PRIVATE }}'
        # preshared_key: '${{ secrets.PRESHARED }}'
        keepalive: '${{ secrets.KEEPALIVE }}'
    - name: Set capabilities on node
      run: sudo setcap cap_net_admin+eip `which node`
    - name: Test typescript
      run: npm run test
    - name: Create artifact
      run: npm pack
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: tarball-node-${{ matrix.node-version }}
        path: homelabsio-wgctrl-*.tgz
        if-no-files-found: warn