name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: CI
      run: npm ci
    - name: Format
      run: npm run format
    - name: Lint
      run: npm run lint
    - name: Build gyp
      run: npm run build-gyp
    - name: Build ts
      run: npm run build-ts
    - name: Test
      run: npm run test
    - name: Pack
      run: npm pack
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: tarball-node-${{ matrix.node-version }}
        path: homelabsio-wgctrl-*.tgz
        if-no-files-found: warn