name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      # with:
      #   node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Format typescript
      run: npm run format
    - name: Lint typescript
      run: npm run lint-ts
    # - name: Lint commits
    #   run: npm run lint-commit
    - name: Build gyp
      run: npm run build-gyp
    - name: Build typescript
      run: npm run build-ts
    - name: Test typescript
      run: npm run test
    - name: Create artifact
      run: npm pack
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: tarball-node-${{ matrix.node-version }}
        path: homelabsio-wgctrl-*.tgz
        if-no-files-found: warn